services:
  postgresql18:
    image: postgres:18
    container_name: primary
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB:       demo
    ports:
      - "5432:5432"
    volumes:
      - primary-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pg-demo

volumes:
  primary-data:

networks:
  pg-demo:
    driver: bridge
