services:
  postgresql18:
    image: postgres:18
    container_name: primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - primary-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pg-demo
    command: >
      postgres
      -c max_connections=10
      -c shared_buffers=256MB
      -c work_mem=4MB

  sysbench:
    build: .
    container_name: sysbench
    depends_on:
      postgresql18:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASSWD: chamgeme
      DB_NAME: demo
      DB_HOST: postgresql18
      DB_PORT: 5432
    volumes:
      - ./benchmark.sh:/benchmark.sh
    networks:
      - pg-demo

volumes:
  primary-data:

networks:
  pg-demo:
    driver: bridge
