services:
  primary:
    image: mysql:8.4
    container_name: primary
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE:      demo
      MYSQL_USER:          demo
      MYSQL_PASSWORD:      changeme
    ports:
      - "3306:3306"
    volumes:
      - primary-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padminpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - proxysql-demo

volumes:
  primary-data:

networks:
  proxysql-demo:
    driver: bridge
